---
- name: Create lancache-monolithic container
  community.docker.docker_container:
    name: lancache-monolithic
    image: lancachenet/monolithic:latest
    # pull: true
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    env: "{{ __lancache_env.monolithic }}"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - "{{ lancache_cache_root }}/cache:/data/cache"
      - "{{ lancache_cache_root }}/logs:/data/logs"

- name: Create lancache-dns container
  community.docker.docker_container:
    name: lancache-dns
    image: lancachenet/lancache-dns:latest
    # pull: true
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    env: "{{ __lancache_env.dns }}"
    ports:
      - 53:53/udp
      - 53:53/tcp
