---
- name: Create compose directory
  ansible.builtin.file:
    path: '{{ lancache_compose_dir }}'
    state: directory
    mode: 0775
  become: true
- name: Template docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    mode: 0775
    dest: '{{ lancache_compose_dir }}/docker-compose.yaml'
  become: true
- name: Copy update_containers file
  ansible.builtin.copy:
    src: templates/update_containers.sh
    mode: 0775
    dest: '{{ lancache_compose_dir }}/update_containers.sh'
  become: true
- name: Create and start services
  community.docker.docker_compose:
    project_src: '{{ lancache_compose_dir }}'
  register: output
- name: Show compose results
  ansible.builtin.debug:
    var: output
