---
- name: Create lancache-monolithic container
  community.docker.docker_container:
    name: lancache-monolithic
    image: lancachenet/monolithic:latest
    # pull: true
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    env: "{{ lancache_monolithic_env }}"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /mnt/lancache/cache:/data/cache
      - /mnt/lancache/logs:/data/logs

- name: Create lancache-dns container
  community.docker.docker_container:
    name: lancache-dns
    image: lancachenet/lancache-dns:latest
    # pull: true
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    env: "{{ lancache_dns_env }}"
    ports:
      - 53:53/udp
      - 53:53/tcp
